name: Playwright Tests & Report Deployment
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Paule-Portfolio

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm install
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # 1. Build the production application files
    - name: Build local app (Vite)
      run: npm run build

    # 2. Force-start Vite's preview server in the background and wait a few seconds for it to boot up
    # - name: Start Vite Preview Server
    #   run: |
    #     npx vite preview --port 5173 --host 127.0.0.1 &
    #     sleep 5

    # 3. Execute tests against the background server
    - name: Upload Report Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: Paule-Portfolio/playwright-report/

  deploy:
    needs: test
    # This line ensures it only triggers when you push/merge to master or main
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        
      - name: Deploy Production to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}