name: Playwright Tests & Report Deployment
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Paule-Portfolio

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm install
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # 1. Build the production application files
    - name: Build local app (Vite)
      run: npm run build

    # 2. Force-start Vite's preview server in the background and wait a few seconds for it to boot up
    # - name: Start Vite Preview Server
    #   run: |
    #     npx vite preview --port 5173 --host 127.0.0.1 &
    #     sleep 5

    # 3. Execute tests against the background server
    - name: Run Playwright tests
      run: npx playwright test --update-snapshots

    - name: Upload Report Artifact
      uses: actions/upload-pages-artifact@v3
      if: always()
      with:
        path: Paule-Portfolio/playwright-report/

  deploy:
    needs: test
    if: always()
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
